// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abzhalnvmtbkqgmwywhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiemhhbG52bXRia3FnbXd5d2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3Mjk2NzAsImV4cCI6MjA5MzMwNTY3MH0.ynQ8sXe4jSNOinaYPPjSdB_71H4CA2e8xd6tjpdejlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);