-- ====================================================================
-- Beyond Barista Academy - Seed 24-Module Barista Curriculum into Neon
-- Generated by scripts/generate-barista-neon-seed.mjs from
-- src/data/baristaCurriculum.ts - do not hand-edit, regenerate instead.
-- Matches the LIVE Neon schema (integer ids, sort_order, body, minutes).
-- Added alongside the existing 23-course catalog, not replacing it.
-- ====================================================================

DO $$
DECLARE
  v_course_id integer;
  v_mod_ids integer[] := '{}';
  v_mid integer;
BEGIN
  INSERT INTO public.courses (slug, title, level, duration, description, image, price, instructor, capacity, status, created_at)
  VALUES (
    'professional-barista-mastery-24-module',
    'Professional Barista Mastery & Coffee Ecosystem (24 Modules + Certification)',
    'Advanced',
    '24 weeks',
    'The complete 24-module professional barista program from bean origin to roasting, brewing, sensory skills, hospitality management, and entrepreneurship, plus a final certification exam.',
    '/images/barista.jpg',
    'Free',
    'Coach Egide HATEGEKIMANA',
    500,
    'active',
    to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
  )
  ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description
  RETURNING id INTO v_course_id;

  -- Clear any previous modules for this course (cascades to lessons) so this script is idempotent
  DELETE FROM public.modules WHERE course_id = v_course_id;

  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 01: Introduction to Coffee', 1) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 02: Brewing Science', 2) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 03: Roasting Science', 3) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 04: Sensory Skills Fundamentals & Flavor Development', 4) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 05: Green Coffee Grading & Quality Control', 5) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 06: Barista Skills & Espresso Mechanics', 6) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 07: Coffee Shop Operations', 7) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 08: Customer Service & Barista Professionalism', 8) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 09: Menu & Recipe Development', 9) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 10: Prepare Iced and Specialty Drinks', 10) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 11: Basic Cooking Skills for Café Baristas', 11) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 12: Prepare Ice Cream & Affogato Specialties', 12) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 13: Prepare & Understand Drinking Water for Coffee', 13) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 14: Prepare Welcoming Drinks & Food Pairing', 14) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 15: Prepare Hot & Cold Non-Coffee Beverages', 15) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 16: Cleaning & Maintenance of Machine & Grinder', 16) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 17: Tobacco & Cigar Service in Luxury Hospitality', 17) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 18: POS | Point of Sale Operations & Cash Handling', 18) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 19: Coffee Mixology & Cold Brew Cocktails', 19) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 20: Home Barista & Compact Equipment Setup', 20) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 21: Interview Performance & Public Speaking', 21) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 22: Personal Branding for Hospitality Professionals', 22) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 23: Rwandan Barista & Coffee Culture', 23) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Module 24: Beverage Entrepreneurship & Café Business Model', 24) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);
  INSERT INTO public.modules (course_id, title, sort_order) VALUES (v_course_id, 'Final Examination: Comprehensive Barista Certification Exam', 25) RETURNING id INTO v_mid; v_mod_ids := array_append(v_mod_ids, v_mid);

  INSERT INTO public.lessons (module_id, title, body, video_url, minutes, sort_order) VALUES
    (v_mod_ids[1], '1.1 History and Origins of Coffee (Ethiopia to the World)', 'Discover Kaldi the goat herder in Ethiopia, the early trade routes through Yemen (Mocha), the Ottoman Empire coffee houses, and how coffee conquered Europe and the Americas.', 'https://www.youtube.com/watch?v=J3-wH0tO6wY', 15, 1),
    (v_mod_ids[1], '1.2 Coffee Plant Botany: Arabica vs. Robusta', 'Deep dive into Coffea Arabica (Bourbon, Typica, Gesha) versus Coffea Canephora (Robusta). Compare chromosome counts, caffeine levels, lipid percentages, altitude requirements, and flavor profiles.', '', 20, 2),
    (v_mod_ids[1], '1.3 The Global Coffee Belt & Major Producing Regions', 'Learn how terroir, latitude, volcanic soils, rainfall patterns, and shade-grown ecosystems influence body, acidity, and aromatic complexity in Central/South America, East Africa, and Asia-Pacific.', '', 18, 3),
    (v_mod_ids[2], '2.1 The 6 Golden Rules of Manual Extraction', 'Detailed breakdown of coffee-to-water ratios (1:15 to 1:17), water temperature (90-96°C), grind size consistency, turbulence/agitation, filter media selection, and contact duration.', 'https://www.youtube.com/watch?v=1oB1oDrDkHM', 22, 1),
    (v_mod_ids[2], '2.2 Manual Pour-Over Devices (V60, Chemex, Kalita Wave)', 'Step-by-step pouring techniques for Hario V60 conical filters, thick paper Chemex filtration, and flat-bottom Kalita Wave geometry. Master bloom phase gas release.', 'https://www.youtube.com/watch?v=AI4ynXzkSQo', 25, 2),
    (v_mod_ids[2], '2.3 Full Immersion vs. Percolation Mechanics', 'Compare French Press and AeroPress full-immersion extraction against gravity percolation. Measure total dissolved solids (TDS) and extraction yield percentages (18-22%).', '', 15, 3),
    (v_mod_ids[3], '3.1 Heat Transfer Mechanics in Drum & Air Roasters', 'Examine convective hot-air flow and conductive drum wall contact. Follow moisture evaporation, endothermic drying phases, and Rate of Rise (RoR) management.', 'https://www.youtube.com/watch?v=uK1XW1b2Rlg', 20, 1),
    (v_mod_ids[3], '3.2 Chemical Transformations: Maillard Reaction & First Crack', 'Analyze how amino acids and reducing sugars break down during the Maillard reaction, generating aromatic pyrazines, furans, and organic acids. Pinpoint First Crack acoustic release.', '', 25, 2),
    (v_mod_ids[3], '3.3 Light, Medium, Dark Roast Profiles & Agtron Scoring', 'Evaluate light cinnamon/city roasts, medium full-city roasts, and dark French/Italian roasts using infrared Agtron spectrophotometer scale numbers.', '', 15, 3),
    (v_mod_ids[4], '4.1 SCA Standard Cupping Protocol & Triangulation', 'Set up an official SCA cupping table: 8.25g coffee per 150ml water, 4-minute steep, crust break technique, olfactory fragrance assessment, and scoring sheets.', 'https://www.youtube.com/watch?v=83pQc40p-tM', 30, 1),
    (v_mod_ids[4], '4.2 The SCA Coffee Taster''s Flavor Wheel & Olfactory Memory', 'Navigate floral, fruity (enzymatic), roasted, caramelized (sugar brown), and dry distillation note categories. Practice identifying sensory references.', '', 20, 2),
    (v_mod_ids[5], '5.1 SCA Green Coffee Defect Classification', 'Identify primary defects (full black, full sour, pod/cherry, fungus damage) and secondary defects (partial sour, broken/chipped, insect damage, parchment).', '', 25, 1),
    (v_mod_ids[5], '5.2 Moisture Content, Density & Bean Screen Sizing', 'Utilize digital moisture meters (target 10.5% - 11.5%), water activity meters (aW < 0.60), and brass screen mesh sizes (14/16/18 AA/AB grades).', '', 20, 2),
    (v_mod_ids[6], '6.1 Espresso Extraction Mechanics & Dialing-In', 'Set up 18g dose in a double portafilter basket for a 36g yield in 27-30 seconds at 9 bar pressure and 93°C temperature. Adjust micro-grind collars.', 'https://www.youtube.com/watch?v=g2Wd4e2D3eA', 35, 1),
    (v_mod_ids[6], '6.2 Milk Steaming, Texturing & Latte Art Foundations', 'Aeration vs. stretching phase, vortex circulation to 60-65°C, pitcher angle, and free-pour techniques for the Heart, Rosetta, and Tulip patterns.', 'https://www.youtube.com/watch?v=R9_u2wXf398', 30, 2),
    (v_mod_ids[7], '7.1 Efficient Bar Ergonomics & Workflow Lines', 'Design linear and triangular bar layouts: Order POS -> Grinder -> Espresso Machine -> Milk Station -> Hand-off Counter.', '', 20, 1),
    (v_mod_ids[7], '7.2 Inventory Control, FIFO & Waste Minimization', 'Implement First-In-First-Out stock rotation for fresh roasts, milk cartons, syrups, and packaging. Track daily waste logs.', '', 18, 2),
    (v_mod_ids[8], '8.1 The Art of Genuine Rwandan Hospitality (Ikaze)', 'Welcome guests with warmth, eye contact, and active listening. Create custom beverage suggestions based on preference profiles.', 'https://www.youtube.com/watch?v=VnJ5A2e-Z9Q', 20, 1),
    (v_mod_ids[8], '8.2 Conflict Resolution & Handling Service Recovery (LAST Method)', 'Apply the Listen, Apologize, Solve, and Thank protocol for remaking incorrect drinks, dietary misunderstandings, or wait-time delays.', '', 15, 2),
    (v_mod_ids[9], '9.1 Drink Costing Formulas & Profit Margins', 'Calculate Cost of Goods Sold (COGS) per cup: espresso dose cost + milk volume cost + cup/lid cost + syrup cost to maintain 15-22% COGS.', '', 22, 1),
    (v_mod_ids[9], '9.2 Designing Balanced Classic & Contemporary Coffee Menus', 'Structure menu categories: Espresso Classics, Filter Pour-Overs, Signature Cold Brews, Herbal/Tea Infusions, and Non-Dairy Alternatives.', '', 20, 2),
    (v_mod_ids[10], '10.1 Cold Brew Immersion vs. Japanese Flash Brew Technique', 'Compare 18-hour cold immersion steeped in Toddy systems vs. direct pour-over over ice (flash brewing) to preserve delicate aromatic top notes.', 'https://www.youtube.com/watch?v=Jj4jV7bK3A4', 25, 1),
    (v_mod_ids[10], '10.2 Craft Syrups & Blended Iced Beverages (Frappés)', 'Cook 1:1 and 2:1 simple syrups infused with vanilla bean, salted caramel, cardamom, or cinnamon. Emulsify blended iced frappes.', '', 20, 2),
    (v_mod_ids[11], '11.1 Essential Kitchen Safety, Sanitation & Knife Handling', 'Master chef knife grip, claw position cutting technique, cutting board color coding (raw meat vs. produce vs. dairy), and cross-contamination rules.', '', 20, 1),
    (v_mod_ids[11], '11.2 Café Breakfast Sandwiches & Gourmet Toasties', 'Prepare avocado sourdough toast with poached eggs, croque monsieur, and toasted panini pairings designed for quick café counter service.', 'https://www.youtube.com/watch?v=9XW1rA7Q5a8', 25, 2),
    (v_mod_ids[12], '12.1 Ice Cream & Gelato Fat-Sugar Balance', 'Differentiate French custard ice cream from Italian gelato (lower butterfat, less overrun air). Maintain ideal scoop temperatures (-12°C).', '', 18, 1),
    (v_mod_ids[12], '12.2 The Authentic Affogato al Caffè & Artisan Sundaes', 'Pour a fresh double espresso shot directly over a dense scoop of vanilla bean gelato. Add crushed hazelnut or amaretto garnishes.', 'https://www.youtube.com/watch?v=0k5X2N3zV4w', 15, 2),
    (v_mod_ids[13], '13.1 SCA Water Specifications & Chemical Components', 'Target 150 mg/L TDS, 50-70 mg/L total hardness (Ca2+ and Mg2+), 40 mg/L alkalinity, and neutral 7.0 pH for ideal extraction without scale buildup.', '', 22, 1),
    (v_mod_ids[13], '13.2 Water Filtration Systems (Carbon, Softeners, RO Remineralization)', 'Evaluate activated carbon block filters, ion-exchange softening resins, and Reverse Osmosis with calcifying bypass valves.', '', 20, 2),
    (v_mod_ids[14], '14.1 Crafting Sparkling & Herbal Welcome Drinks', 'Prepare sparkling ginger-lemon waters, hibiscus (Bissap/Karkadeh) coolers, and cold infused herb waters served to arriving café guests.', 'https://www.youtube.com/watch?v=3V4x9X2zW10', 15, 1),
    (v_mod_ids[14], '14.2 Complementary & Contrast Food Pairing Principles', 'Pair bright Ethiopian Yirgacheffe (citrus/floral) with lemon tarts, and heavy-bodied Sumatra (earthy/spicy) with dark chocolate desserts.', '', 20, 2),
    (v_mod_ids[15], '15.1 Tea Categorization, Steeping Temperatures & Timing', 'Steep White/Green teas (70-80°C, 2-3 mins), Oolong (85°C), Black Teas (95°C, 4-5 mins), and Rooibos/Herbal infusions (100°C, 5-7 mins).', '', 20, 1),
    (v_mod_ids[15], '15.2 Ceremonial Grade Matcha & Masala Chai Latte Techniques', 'Whisk Japanese ceremonial matcha in a Chawan bowl with a bamboo Chasen. Simmer whole-spice Assam black tea for authentic Chai.', 'https://www.youtube.com/watch?v=1V4x9X2zW10', 22, 2),
    (v_mod_ids[16], '16.1 Daily Backflossing & Chemical Portafilter Bath Routine', 'Perform blind filter basket backflushing using espresso cleaning detergent (Cafiza/Puly Caff). Soak portafilters, shower screens, and steam tips.', 'https://www.youtube.com/watch?v=5X4x9X2zW10', 20, 1),
    (v_mod_ids[16], '16.2 Grinder Burr Cleaning, Alignment & Replacement Intervals', 'Vacuum bean hoppers, remove rancid coffee oils with Urnex Grindz pellets, inspect burr wear, and replace flat burrs after 500-800 kg throughput.', '', 18, 2),
    (v_mod_ids[17], '17.1 Cigar Anatomy, Vitolas & Humidor Maintenance', 'Identify wrapper (capa), binder (capote), and filler (tripa) leaves. Maintain 68-72% relative humidity and 18-20°C in Spanish cedar humidors.', '', 20, 1),
    (v_mod_ids[17], '17.2 Elegant Cigar Service, Cutting, Cedar Torch Lighting & Pairings', 'Demonstrate guillotine cut vs. V-cutter vs. punch. Toast the foot with odorless butane lighter or cedar spill. Pair full-bodied Habano cigars with dark roasts.', 'https://www.youtube.com/watch?v=7X4x9X2zW10', 20, 2),
    (v_mod_ids[18], '18.1 POS Order Entry, Custom Modifiers & Table Management', 'Input seat orders quickly, add milk modifications (oat, almond, skim), adjust syrup levels, process split checks, and send tickets to kitchen/bar displays.', 'https://www.youtube.com/watch?v=8X4x9X2zW10', 20, 1),
    (v_mod_ids[18], '18.2 Cash Float Balancing, Mobile Money (MTN MoMo) & Z-Report Audits', 'Count opening float cash, reconcile mobile money payments, process refund overrides, and print daily Z-report financial summaries.', '', 18, 2),
    (v_mod_ids[19], '19.1 The Science of Shaking the Perfect Espresso Martini', 'Shake 45ml Vodka, 30ml fresh hot espresso, 20ml Kahlúa/coffee liqueur, and 10ml simple syrup over hard ice to build a thick, velvety foam head.', 'https://www.youtube.com/watch?v=9X4x9X2zW10', 22, 1),
    (v_mod_ids[19], '19.2 Classic Irish Coffee & Layered Cream Float Etiquette', 'Pre-heat glass, dissolve brown sugar into hot filter coffee, add Irish Whiskey, and float lightly whipped double cream gently over the back of a warm spoon.', 'https://www.youtube.com/watch?v=0Y4x9X2zW10', 20, 2),
    (v_mod_ids[20], '20.1 Optimizing Home Espresso Setups (Gaggia, Breville, DeLonghi)', 'Tips for unpressurized baskets, PID temperature controllers, OPV valve adjustments to 9-bar, and precision hand grinders (1Zpresso, Comandante).', '', 20, 1),
    (v_mod_ids[20], '20.2 Troubleshooting Home Extraction & Steaming Issues', 'Solve channel breakthrough, slow warm-up times, weak single-boiler steam pressure, and scale buildup in home water tanks.', '', 15, 2),
    (v_mod_ids[21], '21.1 Crushing the Practical Barista Bench Audition', 'What head judges look for during 15-minute bench auditions: station cleanliness, grind calibration speed, beverage consistency, and calm under pressure.', 'https://www.youtube.com/watch?v=1Z4x9X2zW10', 20, 1),
    (v_mod_ids[21], '21.2 Articulating Coffee Knowledge & Hospitality Storytelling', 'Practice answering behavioral interview questions, explaining processing methods confidently to guests, and speaking clearly in front of panels.', '', 18, 2),
    (v_mod_ids[22], '22.1 Crafting a High-Impact Barista Resume & LinkedIn Profile', 'Highlight SCA certifications, BBA credentials, speed of service metrics, customer satisfaction ratings, and coffee equipment proficiencies.', '', 20, 1),
    (v_mod_ids[22], '22.2 Coffee Content Creation & Social Media Branding', 'Showcase latte art progress, origin trips, flavor tasting notes, and coffee tutorial reels on Instagram and TikTok to attract premium job offers.', '', 18, 2),
    (v_mod_ids[23], '23.1 The History of Rwandan Specialty Coffee (CWS & Washing Stations)', 'Explore how Rwanda recovered to become a global specialty coffee powerhouse known for clean, sparkling citric acid, floral aromas, and red fruit notes.', 'https://www.youtube.com/watch?v=2Z4x9X2zW10', 25, 1),
    (v_mod_ids[23], '23.2 Kigali''s Specialty Coffee Wave & Local Farmers Support', 'Spotlight leading local roasters and cafés in Kigali. Understand fair-trade practices, direct trade models, and supporting women coffee farmers in Rwanda.', '', 20, 2),
    (v_mod_ids[24], '24.1 Building a Café Business Plan & Financial Feasibility Study', 'Model startup CapEx (espresso machine, grinder, fit-out, licenses) vs. monthly OpEx (rent, wages, beans, utilities, COGS) to reach break-even.', '', 30, 1),
    (v_mod_ids[24], '24.2 Mobile Coffee Carts & Pop-Up Event Catering Models', 'Design low-cost, high-margin mobile espresso setups powered by gas/battery systems for corporate events, weddings, and festivals.', 'https://www.youtube.com/watch?v=3Z4x9X2zW10', 22, 2),
    (v_mod_ids[25], 'Final Exam Study Guide & Theory Summary', 'Review key formulas, extraction times, water parameters, defect classifications, food safety protocols, and customer service standards before starting the final exam.', '', 30, 1),
    (v_mod_ids[25], 'Official Final Barista Certification Exam (100% Passing Threshold: 80%)', 'Launch the final 50-question comprehensive examination. Test your knowledge across all 24 modules. Successful completion generates your downloadable, shareable, QR-verified Beyond Barista Academy Certificate!', '', 60, 2);
END $$;
